### PR TITLE
Add Piecewise FastSRM

### PR DESCRIPTION
**Pull request by hugorichard**
This PR is a copy of the piecewise SRM package of Thomas. 
It uses the last version of FastSRM. This is relevant for #49

### CODE REVIEW

**Comment by bthirion** [comment]
@thomasbazeille would you mind taking a look at that ? Let me know if you can't.
It seems to be a mere ssh key issue.
Best,

**Comment by thomasbazeille** [comment]
Sorry for the (huge) delay, I'll check it ASAP

**Comment by emdupre** [comment]
🙋  I'm happy to pick this up ! @hugorichard I assume you don't have time to fix the merge conflicts here ;  I'll plan to open a superseding PR with these changes unless I hear otherwise from you. Thanks !

**Comment by hugorichard** [comment]
Hello Elizabeth,
Indeed, I won't have time to merge conflicts.
Fill free to do as you wish :)
Thanks a lot for taking care of this.

Le mar. 5 sept. 2023 à 22:17, Elizabeth DuPre ***@***.***> a
écrit :

**Comment by emdupre** [comment]
Closing now that #70 has been merged. Thank you, @hugorichard !

**Comment by bthirion** [comment]
Thx to all ! 
Best,

**Pull request closed without merging**
