### PR TITLE
Make POT an optional dependency

### PR DESCRIPTION
**Pull request by thomasbazeille**
to solve #18

### CODE REVIEW

**Comment by thomasbazeille** [comment]
Ready for review.

**Comment by bthirion** [comment]
We really need to setup travis, to see whether PRs break anything, as currently we're working in the dark.
So please, don't update any more the library without travis validation !

**Comment by thomasbazeille** [comment]
Actually I have CircleCI running the test on my fork at every push and
nothing is broken. you should set it up as well for the Parietal account
and this project and the config.yml will take care lf the rest. We can do
that next week.

**Comment by thomasbazeille** [comment]
@bthirion cf the comment above

**Comment by bthirion** [comment]
Merging.

**Pull request merged**
